### ISSUE TITLE
go build . 报错

### ISSUE THREAD

**Issue by Esword618** [jinzhongmin/goncnn-examples#1]
`go build .`报错：
```
go build github.com/jinzhongmin/goffi/pkg/ffi:
# pkg-config --cflags  -- libffi
pkg-config: exec: "pkg-config": executable file not found in %PATH%
# github.com/jinzhongmin/goffi/pkg/dlfcn
..\..\..\pkg\mod\github.com\jinzhongmin\goffi@v0.0.0-20231008052451-133422fc6331\pkg\dlfcn\dlfcn.go:6:10: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
          ^~~~~~~~~
compilation terminated.
```

**Comment by jinzhongmin** [comment]
windows 下的吗，windows下装一下msys2，在msys2中安装gcc，将bin目录加到环境变量

**Comment by jinzhongmin** [comment]
安装一下 https://github.com/jinzhongmin/goffi

**Comment by jinzhongmin** [comment]
[yolov5-example.zip](https://github.com/jinzhongmin/goncnn-examples/files/13761246/yolov5-example.zip)

**Comment by jinzhongmin** [comment]
[deeplabv3-plus-example.zip](https://github.com/jinzhongmin/goncnn-examples/files/13770505/deeplabv3-plus-example.zip)

**Comment by Esword618** [comment]
感谢大佬！

**Comment by Esword618** [comment]
大佬还是报这个错误，是不是需要吧ncnn的文件配置环境变量？
```
go build github.com/jinzhongmin/goffi/pkg/ffi:
# pkg-config --cflags  -- libffi
pkg-config: exec: "pkg-config": executable file not found in %PATH%
# github.com/jinzhongmin/goffi/pkg/dlfcn
..\..\pkg\mod\github.com\jinzhongmin\goffi@v0.0.0-20231008052451-133422fc6331\pkg\dlfcn\dlfcn.go:6:10: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
          ^~~~~~~~~
compilation terminated.
```

**Comment by Esword618** [comment]
我下载了msys2，并且安装了
```
pacman -S mingw-w64-x86_64-dlfcn
pacman -S mingw-w64-x86_64-libffi
```
并配置了环境变量
![image](https://github.com/jinzhongmin/goncnn-examples/assets/73058062/10268b42-2459-4d70-bb0c-dc31640876f6)
但是函数报错：
```
go build github.com/jinzhongmin/goffi/pkg/ffi:
# pkg-config --cflags  -- libffi
pkg-config: exec: "pkg-config": executable file not found in %PATH%
# github.com/jinzhongmin/goffi/pkg/dlfcn
..\..\pkg\mod\github.com\jinzhongmin\goffi@v0.0.0-20231008052451-133422fc6331\pkg\dlfcn\dlfcn.go:6:10: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
          ^~~~~~~~~
compilation terminated.
```

**Comment by jinzhongmin** [comment]
D:\msys64 \mingw64\bin 把这个目录加到环境变量PATH里

**Comment by Esword618** [comment]
解决了，是这个https://github.com/jinzhongmin/goffi 里面没说安装pkg-config，我以为仅仅安装两个就好了。建议加一下。

**Comment by Esword618** [comment]
下面是我用yolov5训练的模型，但是我在使pnnx转化为ncnn的模型后，使用你的yolov5s-exmple的例程调用我的模型进行识别，发现有报错，大佬可以帮忙看看吗，这个对于我有点难度，不知道怎么入手。
下面是报错：
```
panic: runtime error: slice bounds out of range [:2008210] with capacity 277200

goroutine 66 [running]:
main.main.func1(0xc2e87c?, 0x6270)
        E:/goproject/src/goncnn-examples/defect-identification/main.go:99 +0x288
github.com/anthonynsimon/bild/parallel.Line.func1()
        E:/goproject/src/pkg/mod/github.com/anthonynsimon/bild@v0.13.0/parallel/parallel.go:33 +0x55
created by github.com/anthonynsimon/bild/parallel.Line in goroutine 1
        E:/goproject/src/pkg/mod/github.com/anthonynsimon/bild@v0.13.0/parallel/parallel.go:31 +0xa5
panic: runtime error: slice bounds out of range [:1472710] with capacity 277200
```
[defect-identification.zip](https://github.com/jinzhongmin/goncnn-examples/files/13804288/defect-identification.zip)

**Comment by jinzhongmin** [comment]
[main.zip](https://github.com/jinzhongmin/goncnn-examples/files/13806530/main.zip)
输出形状跟训练时的类别数量有关，加个类别数量的变量就可以了

**Comment by Esword618** [comment]
好的，谢谢大佬
